### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by ChaosCom** [streamlink/streamlink-portable#15]
EDIT 1: Actually the executable is still being generated, I have no idea what the impact of the error message is.

Release 0.6.0 fails with the following ERRORS.TXT:

> The following dependencies are missing:
> six
> appdirs
> packaging
> pyparsing
> urllib3
> idna
> chardet
> certifi
> 
> Possible solutions:
> -Check if a new version is available at https://github.com/streamlink/streamlink-portable
> -Manually add the dependencies to 'Files\Resources\Streamlink_Patches.zip' and build again.
> -Use an older ZIP archive rather than latest snapshot

**Comment by yomammary** [comment]
I have the same issue.
Using Windows 10 x64 1607 and the latest streamlink-portable.
Also note that I'm generating the portable .exe file, it gets created but doesn't work.

**Comment by gravyboat** [comment]
Hmm, there were some dependency issues over here: https://github.com/streamlink/streamlink/issues/945 I wonder if that's related. @RosadinTV Have you been able to successfully build the latest portable?

**Comment by RosadinTV** [comment]
Thanks for the report.
I will fix it soon 😺

**Comment by RosadinTV** [comment]
Fixed in https://github.com/streamlink/streamlink-portable/commit/0d6c659836422a0e524581e65d7b078fb247f371 🚒

**Comment by yomammary** [comment]
Thank you :)

**Comment by RosadinTV** [comment]
With the introduction of https://github.com/streamlink/streamlink/pull/1020 the issue appeared again.
Releases are generated and working properly but the error report (ERRORS.txt) is incorrect.

**Comment by gravyboat** [comment]
Sorry for creating this hassle for you @RosadinTV!

**Comment by RosadinTV** [comment]
@gravyboat No problem, only a couple of modifications are required.
I also like to fix things in my free time 🍬

**Comment by RosadinTV** [comment]
Update: Sorry for the delay, i was busy and sick.
Surely the fix will be ready for today or tomorrow.

**Comment by gravyboat** [comment]
No rush @RosadinTV! I hope you are feeling better.

**Comment by RosadinTV** [comment]
Ready for now (With some additional fixes) 🎆

**Comment by gravyboat** [comment]
@RosadinTV Awesome thanks for fixing that up! @ChaosCom Looks like RosdainTV has been kind enough to put up a pre-release here: https://github.com/streamlink/streamlink-portable/releases can you give that a shot?

**Comment by RosadinTV** [comment]
@gravyboat Maybe it's a little confusing but the organization of the repository would be the following:
:one: "Streamlink for Windows (Source code)" folder ➡️ Contains the source code of the builder program (For developers)
:two: "Streamlink for Windows (Compiled)" folder ➡️ Contains the builder program (ready-to-run) (For end-users that like to be able to generate their own Releases, including nighly builds)
:three: Releases ➡️ Contains ready-to-run portable releases based on the source code available at https://github.com/streamlink/streamlink/releases (Starting with v0.7.0 since it would not make sense to recompile old versions)  (For end-users that only need a working stable release, avoiding the builder program)

It may be necessary to update the documentation, but that is the hardest part because my English is VERY bad, so I have to make sure it does not get so disastrous 😆

**Comment by gravyboat** [comment]
Hah I understand completely @RosadinTV! Your English is perfectly fine, please try to not be so hard on yourself.
