### ISSUE TITLE
I downloaded a new updated version of streamlink portable for windows. I ran it once. My windows command line font settings changed. The old setting is not an option to go back to anymore, ever, it seems.

### ISSUE THREAD

**Issue by left1000** [streamlink/streamlink-portable#30]
I downloaded a new updated version of streamlink portable for windows. I ran it once. My windows command line font settings changed. The old setting is not an option to go back to anymore, ever, it seems.

So running streamlink, the newest version, for the first time changed my font in the current command line windows on windows 7. I thought, oh, no big deal, my other command line windows still have the old font setting I like. After having closed all my command lines in windows, and also having rebooted, I don't have the chance to go back.

The original font was "Raster Fonts" 10x twenty something and the new font is "Raster Fonts" 10x18 10x18 is as big as it goes now, it won't let me select large font anymore, this makes it very hard to read my command line. It doesn't even make sense to me how streamlink could've changed my system in such a way as to remove/delete several basic default font options from my computer.... but uh it probably shouldn't've done that, now I have to either go blind or live with Consolas or Lucida Console which can still go large.

I'm sure I'll get over having my large font be fat and stylized instead of thin and simple. Still, whatever caused this is a flaw in my mind and my old copy of streamlink never did this.

Here's the exact version of the version in question:
"
v0.14.2 - Git 215d789
"

**Comment by RosadinTV** [comment]
Hi.
The program doesn't change system font or any other system setting.
I could't reproduce the bug either.

CMD:
![image](https://user-images.githubusercontent.com/13382316/46522971-aa9fa080-c85a-11e8-803c-f23b4644aa04.png)
Latest Stable:
![image](https://user-images.githubusercontent.com/13382316/46523044-e89cc480-c85a-11e8-8b78-e37d47f6687b.png)

**Comment by left1000** [comment]
By default windows doesn't have access to any of those fonts as command line choices. Although it does appear like fuentes de mapa de bits is "Raster Fonts" but since your console setup isn't the vanilla windows7 default, it might reproduce the bug if it were? Thanks for at least considering the issue, even if maybe I'm somehow just entirely wrong.

**Comment by gravyboat** [comment]
@left1000 I appreciate you adding some notes on this. What we'll do is leave the issue open for a few days. If someone else runs into it we can keep it open and see if something weird is going on. This might not apply since you are on Windows 7 and this is for Windows 10, but I'm wondering if somehow the system fonts got messed up? Can you try this: https://superuser.com/a/234624/199412 and see if somehow it's the system defaults missing? Note that this will restore all your settings to default. You could also try a system restore to before the point where you installed Streamlink, then maybe see if there's something else going on?

I wish I had a better suggestion but I can't find much on this issue for Windows 7, there's a bunch of people reporting issues with fonts vanishing on Windows 10, but that seems update related..

**Comment by left1000** [comment]
To clarify, I never installed streamlink, I just unzipped it and ran the .exe which is what makes it even less likely that it messed up my system fonts.

I went to font settings and clicked restore default font settings, but all it did was make the button instantly grey out and then do nothing at all.

**Comment by gravyboat** [comment]
The installed version and the portable version should never collide because of the way they are designed (the portable is specifically designed not to rely on system dependencies for that reason) so it's highly unlikely that would be the problem. Hmm it's odd the font settings didn't reset your modifications to default, I thought it would have...

**Comment by left1000** [comment]
Well technically none of my font changes are font changes, like I set my system settings to 125% DPI, but that's not part of the font control panel, and I enabled japanese "style" by enabling it in language settings, again, not "font settings". I've never intentionally changed anything in the font's section of my control panel before ever. Hence my previous claim of "default" so, most likely, it just changed itself from default to default, and there was no work to do.

**Comment by left1000** [comment]
I know this is probably irrelevent, but the font I want? It's still listed as the default font for windows console! I randomly clicked on defaults instead of "properties" just now and saw Raster Fonts: Terminal 10x22 listed and it looked just like I wanted it to, unfortunately, despite being the "default" in the "defaults" selection, it's still not being used.
