### ISSUE TITLE
Update for 1.1.1

### ISSUE THREAD

**Issue by Rubeek** [streamlink/streamlink-portable#33]
Sorry to open a new ticket for this but any chance this gets updated to 1.1.1? Thanks

**Comment by Vangelis66** [comment]
@Rubeek 
With due respect, you can always use the application bundle [**Streamlink for Windows (Compiled).zip**] kindly provided by @RosadinTV to build yourself either the **latest stable release** (**1.1.1** that you ask...) or the **current master HEAD** of streamlink code (git-20190403-g4648d67); at this time of writing, _both are exactly the same_ 😉 :

![Streamlink111Portable](https://user-images.githubusercontent.com/9669492/55760673-7608dd80-5a65-11e9-8783-cd74a212bcb0.jpg)

FWIW, I managed to compile it in under 4min in my old Vista SP2 32-bit (.NET FW 4.6.1 installed - LAST version that installs under Vista) laptop, so you probably shouldn't have any trouble yourself with a more recent machine... And since Python **3.6.x** _continues to support Vista_, I have no issues running the compiled application: 

![SL111](https://user-images.githubusercontent.com/9669492/55760898-35f62a80-5a66-11e9-8a2c-5216e8c6f028.jpg)

@RosadinTV: 
Many thanks again for your invaluable efforts; would you please kindly consider: 
1. Updating 7-zip modules inside your application bundle (at version 17.01; latest is 19.00)
2. Updating embedded Python 3.6.3 to (at least) **3.6.8**; this is the last bugfix release for 3.6; from now on, only security releases will be released until 2021 (... I have toyed with the code a bit and managed to update it locally on my setup...).

 I don't know the extent to which current streamlink code is compatible with (latest) Python **3.7**, but your bundle should transition to 3.7 at some point; FTR, latest Python **3.7.3** has just been released!

Warmest greetings! 😄

**Comment by Rubeek** [comment]
Ah I'm an idiot, I was just checking the 'releases' tab. Thanks for explaining that.

**Comment by gravyboat** [comment]
@Vangelis66 Rosadin chose to step down from the project (and we greatly appreciate all the work and time they put in!). If you'd like to make a PR with those changes we can see about merging it. Things might be a bit slow on this portion of the project just because it doesn't have a dedicated maintainer currently.

**Comment by Vangelis66** [comment]
@Rubeek wrote: 

> I was just checking the 'releases' tab

... What was being uploaded in the [Releases](https://github.com/streamlink/streamlink-portable/releases/latest) section was purely out of courtesy/for convenience purposes, for those that couldn't/wouldn't be bothered to run the actual compiling application 😉 ; more [here](https://github.com/streamlink/streamlink-portable#can-i-download-a-ready-to-use-release-without-using-the-program)...

In light of the new (unfortunate) developments, I'm not certain as to how this specific issue should be _labelled_: `won't fix` or `invalid` (perhaps a member of the organization with writing/uploading rights in this repo could compile v1.1.1 ("portable.exe" variant) and upload it afterwards - just a thought...)?

@gravyboat : 

Hi Forrest 😅 ; I do hope all's well with you! 
As you can probably tell, I haven't followed the streamlink project closely for quite some time now; you know how things go; shift of focus to other fields, etc. 😉 ; as for my streaming/recording needs, they're  mostly covered by `get-iplayer` / `youtube-dl`, take no offence! 😃 

But recently I had a special need for `streamlink`, hence I revisited and compiled the latest portable version - FWIW, I have _always_ used portable iterations of `streamlink`, mostly @RosadinTV's and, at times, the one kindly offered by @beardypig (👍 ).

After what you wrote, I've managed to locate https://github.com/streamlink/streamlink/issues/1992 and, sadly, https://github.com/streamlink/streamlink/issues/1992#issuecomment-472842056 posted on Mar 14th; needless to say, I was deeply saddened, @RosadinTV is a most kind and generous person 👍 ; but such is life... So, to put it simply, while the building application itself currently works OK, it is at risk of breaking (and not getting fixed) with any eventual upstream (i.e. streamlink) new change...

> If you'd like to make a PR with those changes

... As you might remember, I have absolutely **0** coding skills (neither in Python or Visual C); so a PR is highly unlikely, very sorry indeed 😭. As for the nasty manual "hack" I hinted about, in case someone is interested: 

1. After you have extracted `Streamlink for Windows (Compiled)` to a directory of choice, navigate to `.\Files\7zip` directory; those three files inside it should be overwritten with their updated counterparts found inside [7z1900-extra.7z](https://www.7-zip.org/a/7z1900-extra.7z)
2. Navigate to `.\Files\Resources` dir; back-up/delete archive `python-3.6.3-embed-win32.zip`; in that same dir place the updated package [python-3.6.8-embed-win32.zip](https://www.python.org/ftp/python/3.6.8/python-3.6.8-embed-win32.zip) and then **rename** it to `python-3.6.3-embed-win32.zip`.
3. If you're going to compile "portable.exe" variant, edit file `PORTABLE_BUILD.vb` (line 130): 
```diff
- Dim info = New ProcessStartInfo(Chr(34) & Current_EXE_Path & "\Python 3.6.3\python.exe" & Chr(34), Chr(34) & Current_EXE_Path & "\Streamlink\Streamlink.py" & Chr(34) & " --config " & Chr(34) & Current_EXE_Path & "\streamlinkrc" & Chr(34) & " --rtmp-rtmpdump " & Chr(34) & Current_EXE_Path & "\Streamlink\Dependencies\rtmpdump\rtmpdump.exe" & Chr(34) & " --ffmpeg-ffmpeg " & Chr(34) & Current_EXE_Path & "\Streamlink\Dependencies\ffmpeg\ffmpeg.exe" & Chr(34) & " " & InputCommand)
+ Dim info = New ProcessStartInfo(Chr(34) & Current_EXE_Path & "\Python 3.6.8\python.exe" & Chr(34), Chr(34) & Current_EXE_Path & "\Streamlink\Streamlink.py" & Chr(34) & " --config " & Chr(34) & Current_EXE_Path & "\streamlinkrc" & Chr(34) & " --rtmp-rtmpdump " & Chr(34) & Current_EXE_Path & "\Streamlink\Dependencies\rtmpdump\rtmpdump.exe" & Chr(34) & " --ffmpeg-ffmpeg " & Chr(34) & Current_EXE_Path & "\Streamlink\Dependencies\ffmpeg\ffmpeg.exe" & Chr(34) & " " & InputCommand)
```
Then compile as usual...

4. In the finished "product", rename dir `Python 3.6.3` to `Python 3.6.8`; that's it!

 (5. The `Run_StreamlinkPortable.lnk` shortcut in my previous screenshot just targets  
`cmd /k Streamlink.exe -V && Streamlink.exe`, configured to start in current dir...)

Regards 😺

**Comment by bastimeyer** [comment]
I'm going to close the issue, as the repo is unmaintained and will be archived.

See the other available installation methods on Windows:
https://streamlink.github.io/latest/install.html#windows
