### ISSUE TITLE
standalone exe setup fails in win 7 64

### ISSUE THREAD

**Issue by johnthecracker** [streamlink/streamlink-portable#9]
following guidance from beardypig rather than repeating myself
I post the link to this issue in relevant thread, here.

https://github.com/streamlink/streamlink/issues/503

**Comment by RosadinTV** [comment]
Hi, the problem here is we need to add the "iso-639" and "iso3166" packages to "Streamlink for Windows (Compiled)/Files/Resources/Streamlink_Patches.zip" (introduced in #938662fd)
Unfortunately I'm on vacations and i dont have a PC to do this.
I'll be back in less then 2 weeks but if somebody can make a PR will be good.
Also i'm planing some changes in the program to avoid this kind of errors in the future.

**Comment by RosadinTV** [comment]
I'm back, soon i will post the updates.
Also would be cool to add @beardypig portable version to documentation.
I mean https://github.com/beardypig/streamlink-portable so users can choose what they likes.

**Comment by RosadinTV** [comment]
Fixed in https://github.com/streamlink/streamlink-portable/pull/11
